### PR TITLE
Aarav patch v1

### PR DESCRIPTION
**Pull request by human02**
- Added Readme file 
- Added screenshot images

### CODE REVIEW

**Comment by human02** [comment]
@jeel2331 If you added my readme and images, shouldn't you be merging my request? 
You can't just copy the file and label it as your own! Correct me if I am wrong as I am new to Github pull-requests.

**Comment by JeelRajodiya** [comment]
@aaravchandra02 I'm new to GitHub . Could you tell me how do I merge your request?

**Comment by JeelRajodiya** [comment]
> @jeel2331 If you added my readme and images, shouldn't you be merging my request? 
> You can't just copy the file and label it as your own! Correct me if I am wrong as I am new to Github pull-requests.

I'm new to GitHub . Could you tell me how do I merge your request?

**Comment by human02** [comment]
> > @jeel2331 If you added my readme and images, shouldn't you be merging my request?
> > You can't just copy the file and label it as your own! Correct me if I am wrong as I am new to Github pull-requests.
> 
> I'm new to GitHub. Could you tell me how do I merge your request?

It's okay, I am new as well. I guess you first delete the readme and images folder as they do not make sense with your code, they are based on my code. (your might also face conflicts if you do not follow this step, I guess!!)
It's a learning experience for both of us. 🙂 

Then follow the steps given in this link. 
https://help.github.com/en/enterprise/2.13/user/articles/approving-a-pull-request-with-required-reviews#:~:text=Above%20the%20changed%20code%2C%20click,Click%20Submit%20review. 

If you need further help then let me know, I am happy to help!

**Pull request merged**
